"""add applications table

Revision ID: 99da8cc88e7e
Revises: d6e663d294b6
Create Date: 2025-10-22 19:31:30.800235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99da8cc88e7e'
down_revision: Union[str, Sequence[str], None] = 'd6e663d294b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('applied', 'interview', 'offer', 'rejected', 'hired', name='applicationstatus'), server_default='applied', nullable=False),
    sa.Column('applied_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_application_user_job')
    )
    op.create_index('ix_applications_next_action_date', 'applications', ['next_action_date'], unique=False)
    op.create_index('ix_applications_status', 'applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_applications_status', table_name='applications')
    op.drop_index('ix_applications_next_action_date', table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
